name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  check-format:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3.0.0
        with:
          dotnet-version: 5.0.x
      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format
      - name: Run dotnet-format
        run: dotnet format ./ --folder --check --verbosity diagnostic
